#!/bin/bash

self(){
  DIR=$( cd "$( dirname "$0" )/" && pwd)
  echo $DIR
}

$(self)/down

PORT=80

CUSTOMPORT=$(echo $1|egrep "^[0-9]+$"|wc -l)

if [[ "$CUSTOMPORT" -gt "0" ]]; then
    PORT=$1
fi

docker run \
    -dit \
    --name rippled-container \
    -p $PORT:80 \
    -p 5005:5005\
    -p 6006:6006\
    -v $(self)/../config:/config/ \
    rippled

docker logs -f rippled
